#cloud-config

hostname: db
fqdn: db.local.lab

package_upgrade: true

packages:
  - curl
  - wget
  - git
  - vim
  - python3
  - python3-pip
  - sudo

users:
  - name: ansible
    groups: sudo, adm
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3... # Замінити на свій публічний ключ

  - name: student
    groups: sudo, adm
    shell: /bin/bash
    lock_passwd: false
    
  - name: teacher
    groups: sudo, adm
    shell: /bin/bash
    lock_passwd: false

  - name: operator
    groups: sudo
    shell: /bin/bash
    lock_passwd: false

ssh_pwauth: false
disable_root: true

final_message: "DB VM ready! IP: \$HOSTNAME"
